export const ITEMS_IS_LOADING = 'ITEMS_IS_LOADING';
export const ITEMS_HAS_ERRORED = 'ITEMS_HAS_ERRORED';
export const ITEMS_FETCH_DATA_SUCCESS = 'ITEMS_FETCH_DATA_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const CURRENT_PAGE = 'CURRENT_PAGE';
export const CURRENT_SIZE = 'CURRENT_SIZE';